//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceControl.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpensesCategories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpensesCategories()
        {
            this.ExpensesTransactions = new HashSet<ExpensesTransactions>();
            this.RegularExpenses = new HashSet<RegularExpenses>();
        }
    
        public int ExpenseCategoryID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string CategoryName { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpensesTransactions> ExpensesTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegularExpenses> RegularExpenses { get; set; }
    }
}
