//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceControl.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinanceControl_DB_Entities : DbContext
    {
        public FinanceControl_DB_Entities()
            : base("name=FinanceControl_DB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Debts> Debts { get; set; }
        public virtual DbSet<DebtsTransactions> DebtsTransactions { get; set; }
        public virtual DbSet<ExpensesCategories> ExpensesCategories { get; set; }
        public virtual DbSet<ExpensesTransactions> ExpensesTransactions { get; set; }
        public virtual DbSet<IncomeCategories> IncomeCategories { get; set; }
        public virtual DbSet<IncomeTransactions> IncomeTransactions { get; set; }
        public virtual DbSet<RegularExpenses> RegularExpenses { get; set; }
        public virtual DbSet<Reminders> Reminders { get; set; }
        public virtual DbSet<Transfers> Transfers { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
