//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceControl.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoalsTransactions
    {
        public int GoalTransactionID { get; set; }
        public Nullable<int> GoalID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransactionDate { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Goals Goals { get; set; }
    }
}
