//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceControl.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegularExpenses
    {
        public int RegularExpenseID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ExpenseCategoryID { get; set; }
        public decimal Amount { get; set; }
        public string Frequency { get; set; }
        public string Comment { get; set; }
    
        public virtual ExpensesCategories ExpensesCategories { get; set; }
        public virtual Users Users { get; set; }
    }
}
